"""Added Relations

Revision ID: 011cf9b1e007
Revises: 8d512cf04338
Create Date: 2024-04-13 20:51:42.944461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011cf9b1e007'
down_revision = '8d512cf04338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WordSense',
    sa.Column('word_id', sa.String(length=255), nullable=True),
    sa.Column('sense_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['Sense.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['Word.id'], )
    )
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['creator_id'], ['id'])
        batch_op.create_foreign_key(None, 'Translation', ['translation_id'], ['id'])

    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['owner_id'], ['id'])

    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('input_document_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('output_document_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Document', ['output_document_id'], ['id'])
        batch_op.create_foreign_key(None, 'User', ['creator_id'], ['id'])
        batch_op.create_foreign_key(None, 'Document', ['input_document_id'], ['id'])
        batch_op.create_foreign_key(None, 'Organization', ['organization_id'], ['id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('output_document_id')
        batch_op.drop_column('input_document_id')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('translation_id')

    op.drop_table('WordSense')
    # ### end Alembic commands ###
