"""Organization Creation

Revision ID: 172e9aebd1ee
Revises: 8fc780d950c0
Create Date: 2024-04-13 18:47:16.520870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172e9aebd1ee'
down_revision = '8fc780d950c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Organization')
    # ### end Alembic commands ###
