"""Added ONCASCADE in FKs

Revision ID: 27cc3f9bf6de
Revises: 7c3ff517f73f
Create Date: 2024-04-27 15:07:36.790600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cc3f9bf6de'
down_revision = '7c3ff517f73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_constraint('Feedback_creator_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Feedback_translation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Translation', ['translation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['creator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.drop_constraint('Organization_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.drop_constraint('Translation_organization_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Translation_input_document_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Organization', ['organization_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'Document', ['input_document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('User_organization_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Organization', ['organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('User_organization_id_fkey', 'Organization', ['organization_id'], ['id'])

    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Translation_input_document_id_fkey', 'Document', ['input_document_id'], ['id'])
        batch_op.create_foreign_key('Translation_organization_id_fkey', 'Organization', ['organization_id'], ['id'])

    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Organization_owner_id_fkey', 'User', ['owner_id'], ['id'])

    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Feedback_translation_id_fkey', 'Translation', ['translation_id'], ['id'])
        batch_op.create_foreign_key('Feedback_creator_id_fkey', 'User', ['creator_id'], ['id'])

    # ### end Alembic commands ###
