"""Added primary for unknown word

Revision ID: 49c2108d0968
Revises: 600259c44262
Create Date: 2024-05-05 12:36:51.503766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c2108d0968'
down_revision = '600259c44262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UnknownWord',
    sa.Column('written_form', sa.String(length=255), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('possible_translation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['Document.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('written_form', 'reporter_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UnknownWord')
    # ### end Alembic commands ###
