"""Added process time

Revision ID: 600259c44262
Revises: b1c7f04b1e52
Create Date: 2024-05-04 19:36:14.566730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600259c44262'
down_revision = 'b1c7f04b1e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_time', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.drop_column('process_time')

    # ### end Alembic commands ###
