"""Updated length of part of speech

Revision ID: 7c3ff517f73f
Revises: 07547acf3c1a
Create Date: 2024-04-27 12:51:54.679694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3ff517f73f'
down_revision = '07547acf3c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Word', schema=None) as batch_op:
        batch_op.alter_column('part_of_speech',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Word', schema=None) as batch_op:
        batch_op.alter_column('part_of_speech',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
