"""Feedback Creation

Revision ID: 8d512cf04338
Revises: 498e6f25196a
Create Date: 2024-04-13 20:11:21.058871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d512cf04338'
down_revision = '498e6f25196a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=255), nullable=True),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_feedback_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Feedback')
    # ### end Alembic commands ###
