"""Added creation time

Revision ID: 92a8b6bbcaeb
Revises: 011cf9b1e007
Create Date: 2024-04-20 16:27:52.100771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a8b6bbcaeb'
down_revision = '011cf9b1e007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
