"""Updates in some fields

Revision ID: b1c7f04b1e52
Revises: 27cc3f9bf6de
Create Date: 2024-05-04 13:22:25.374814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1c7f04b1e52'
down_revision = '27cc3f9bf6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', postgresql.ENUM('UZ', 'ENG', name='language'), autoincrement=False, nullable=False))

    with op.batch_alter_table('Organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
