"""Word Creation

Revision ID: f70efa096d47
Revises: f9656ee6f95d
Create Date: 2024-04-13 19:51:01.805332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f70efa096d47'
down_revision = 'f9656ee6f95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Word',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('written_form', sa.String(length=50), nullable=False),
    sa.Column('part_of_speech', sa.String(length=10), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'ENG', name='language', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Word')
    # ### end Alembic commands ###
