"""Sense Creation

Revision ID: f9656ee6f95d
Revises: eded552cc6cb
Create Date: 2024-04-13 19:26:32.253620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9656ee6f95d'
down_revision = 'eded552cc6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sense',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('synset_ref', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sense')
    # ### end Alembic commands ###
